/* js/pages/pricing.js — pricing page behaviour (markup is generated by tools/pages/pricing.py).
   1) Currency: CIS visitors (RUB_CC) see RUB, everyone else USD. Two fixed price points per plan, no live FX. Prices live in the HTML
      as data-usd / data-rub attributes, so changing a price = editing tools/pages/pricing.py and regenerating.
   2) {p} templates (data-tpl) are filled with the price in the visitor's currency after translations load.
   3) The volume slider moves the "Recommended" badge to the smallest plan whose monthly quota covers the chosen volume. */
(function(){var O,t=function(k,d){return O.t?O.t(k,d):d};
var RUB_CC=["RU","BY","KZ","KG","TJ","TM","UZ","AM","AZ","MD"];
var QUOTA={free:100,pro:10000,biz:50000};
var STEPS=[100,1000,5000,10000,25000,50000,100000];
/* boot.js appends the site scripts after this file runs, so wait for GESERD (config/geo/i18n) to exist */
function go(n){O=window.GESERD;if(!(O&&O.ready)){if(n<200)return setTimeout(function(){go(n+1)},25);O={}}
(O.ready||Promise.resolve()).then(function(){
  var rub=RUB_CC.indexOf((O.country||"").toUpperCase())>-1,cur=rub?"rub":"usd";
  document.querySelectorAll(".pv").forEach(function(e){e.textContent=e.getAttribute("data-"+cur)});
  document.querySelectorAll("[data-tpl]").forEach(function(e){var tpl=t(e.getAttribute("data-tpl"),"");e.textContent=tpl.replace("{p}",e.getAttribute("data-"+cur))});
  var lg=O.lang||"en";document.querySelectorAll(".ct td.num").forEach(function(e){var n=parseInt(e.textContent.replace(/[^\d]/g,""),10);if(!isNaN(n))e.textContent=n.toLocaleString(lg)});
  var v=document.getElementById("vol");
  function rec(){
    var i=+v.value,vol=STEPS[i];v.style.setProperty("--p",(i/(STEPS.length-1)*100)+"%");
    var pick=vol<=QUOTA.free?"free":vol<=QUOTA.pro?"pro":vol<=QUOTA.biz?"biz":"ent";
    document.querySelectorAll(".plan").forEach(function(c){
      var on=c.getAttribute("data-plan")===pick;c.classList.toggle("hot",on);
      var h=c.querySelector("h3"),b=h.querySelector(".rec");
      if(on&&!b){b=document.createElement("span");b.className="rec";b.textContent=t("pr.rec","Recommended");h.appendChild(b)}
      if(!on&&b)b.remove();
    });
  }
  v.addEventListener("input",rec);rec();
});}
go(0);})();
