/* js/pages/pricing.js — pricing page behaviour (markup is generated by tools/pages/pricing.py).
   1) Currency: CIS visitors see RUB, everyone else USD (prices live in the HTML as data-usd / data-rub).
   2) {p} templates (data-tpl) are filled with the price in the visitor's currency.
   3) Tabs "Transactional" / "Inbound" switch the quota line on each card and the slider scale; the slider moves the Recommended badge to the
      smallest plan whose quota for the active tab covers the chosen volume.
   The page script runs BEFORE boot.js adds the site scripts, so we poll for window.GESERD. */
(function(){var O,t=function(k,d){return O&&O.t?O.t(k,d):d};
var RUB_CC=["RU","BY","KZ","KG","TJ","TM","UZ","AM","AZ","MD"];
var TABS={tx:{q:{free:100,pro:10000,biz:50000},steps:[100,1000,5000,10000,25000,50000,100000]},
          in:{q:{free:25,pro:5000,biz:25000},steps:[25,250,1000,5000,10000,25000,50000]}};
var tab="tx",lg="en";
function fmt(n){return n.toLocaleString(lg)}
function go(n){O=window.GESERD;if(!(O&&O.ready)){if(n<200)return setTimeout(function(){go(n+1)},25);O={}}
 (O.ready||Promise.resolve()).then(init)}
function init(){
  lg=O.lang||"en";
  var rub=RUB_CC.indexOf((O.country||"").toUpperCase())>-1,cur=rub?"rub":"usd";
  document.querySelectorAll(".pv").forEach(function(e){e.textContent=e.getAttribute("data-"+cur)});
  document.querySelectorAll("[data-tpl]").forEach(function(e){e.textContent=t(e.getAttribute("data-tpl"),"").replace("{p}",e.getAttribute("data-"+cur))});
  document.querySelectorAll(".ct td.num").forEach(function(e){var n=parseInt(e.textContent.replace(/[^\d]/g,""),10);if(!isNaN(n))e.textContent=n.toLocaleString(lg)});
  var v=document.getElementById("vol"),marks=document.getElementById("pmarks");
  function draw(){
    var T=TABS[tab],steps=T.steps,last=steps.length-1;
    marks.innerHTML=steps.map(function(s,i){return "<span>"+(i===last?fmt(s)+"+":fmt(s))+"</span>"}).join("");
    document.querySelectorAll(".ptb").forEach(function(b){var on=b.dataset.tab===tab;b.classList.toggle("on",on);b.setAttribute("aria-selected",on)});
    document.querySelectorAll(".plan .q").forEach(function(q){var a=q.querySelector("[data-i18n^='pr.q.']"),b=q.querySelector(".qi");if(!b)return;a.style.display=tab==="tx"?"":"none";b.style.display=tab==="in"?"":"none"});
    rec();
  }
  function rec(){
    var T=TABS[tab],i=+v.value,vol=T.steps[i];v.style.setProperty("--p",(i/(T.steps.length-1)*100)+"%");
    var pick=vol<=T.q.free?"free":vol<=T.q.pro?"pro":vol<=T.q.biz?"biz":"ent";
    document.querySelectorAll(".plan").forEach(function(c){
      var on=c.getAttribute("data-plan")===pick;c.classList.toggle("hot",on);
      var h=c.querySelector("h3"),b=h.querySelector(".rec");
      if(on&&!b){b=document.createElement("span");b.className="rec";b.textContent=t("pr.rec","Recommended");h.appendChild(b)}
      if(!on&&b)b.remove();
    });
  }
  document.querySelector(".ptabs").addEventListener("click",function(e){var b=e.target.closest(".ptb");if(!b||b.dataset.tab===tab)return;tab=b.dataset.tab;v.value=0;draw()});
  v.addEventListener("input",rec);draw();
}
go(0);})();
